# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/', max_length=200)),
            ],
        ),
    ]
