# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoGallery', '0005_auto_20170605_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagewithcomment',
            options={'verbose_name': 'Изображение с комментарием', 'verbose_name_plural': 'Изображения с комментарием'},
        ),
    ]
