# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoGallery', '0007_auto_20170605_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagewithcomment',
            options={'verbose_name': 'изображение с комментарием', 'verbose_name_plural': 'изображения с комментарием'},
        ),
    ]
